fix(validator): limits as warning instead of error
dhis2/aggregate-data-entry-app pull request #357
Opened 2023-09-25 21:45 UTC by Birkbjo

2023-09-25 21:53 UTC, Birkbjo commented on src/shared/stores/entry-form-store.js
> +import { devtools } from 'zustand/middleware'
Note to self: remove

2023-09-25 21:54 UTC, Birkbjo commented on src/shared/stores/entry-form-store.js
> +            const warnings = get().getWarnings() || {}
Note to self: `|| {}` should be unecessary.

2023-09-26 12:13 UTC, KaiVandivier requested changes
Just one request 🙂 the rest looks good!

2023-09-26 12:13 UTC, KaiVandivier commented on src/data-workspace/inputs/validators.js
>          Number.isFinite(limits?.min) &&
Finish refactoring ;) `composeValidators` is kinda janky to use on 0 or 1 validator

2023-09-26 12:41 UTC, Birkbjo commented on src/data-workspace/data-entry-cell/validation-tooltip.js
> +export const ValidationTooltip = ({ children, content, enabled, active }) => {
Renamed `invalid` to `enabled`. After this PR `invalid`-state of the field does not describe the functionality of what this prop actually does. Actually, previously `syncError` was also used to control this prop. The prop actually controls if the tooltip logic is `enabled` - and thus I think that describes the functionality better.

2023-12-11 16:53 UTC, KaiVandivier approved these changes
🚀

2023-12-13 13:10 UTC, merged