fix(integer validation): limit range to the accepted range of the dhis2-core
dhis2/aggregate-data-entry-app pull request #364
Opened 2023-12-12 10:15 UTC by Mohammer5

Fixes [DHIS2-14075](https://dhis2.atlassian.net/browse/DHIS2-14075)

Doc comment from `is-integer.js`:

```/**
 * The `integer` validator of the `@dhis2/ui` library uses
 * `Number.isSafeInterger` to assess whether it the value is a valid integer or
 * not. The range allowed by that methid is -(2^53 - 1) to 2^53 - 1.
 *
 * The `isInteger` validator in the Java core uses the `isValid` method of
 * apache's `IntegerValidator` class (see
 * `dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/MathUtils.java`),
 * which allows an integer range from
 * -2147483648 to 2147483647.
 *
 * This validator re-uses `@dhis2/ui`'s validator but restricts the integer to
 * the range allowed by the Java core.
 */```

2023-12-12 10:48 UTC, stian-sandvold approved these changes

2023-12-12 13:04 UTC, tomzemp requested changes
Approach looks good. I'm not sure the check is working totally as intended (see comments).

Two other things I noticed (not related to your changes):
- I tried testing with an existing data element of type `INTEGER` (BCG Doses Given, which is on Child Health data set) (https://debug.dhis2.org/dev/api/dataElements/s46m5MS0hxu), and there it seemed like any negative values were being rejected by the backend 🤔
- it seems all validations are rerunning any time any value in the form changes. I guess the validation checks aren't very intensive, but that seems like we wouldn't want that?

2023-12-13 13:10 UTC, Birkbjo commented
Note that this touches code that was changed in: https://github.com/dhis2/aggregate-data-entry-app/pull/357

2023-12-14 07:38 UTC, Mohammer5 commented
@Birkbjo interesting! I assume min-max limits are also constrained by the BE's integer validation, but that's just an uneducated guess. Do you know @stian-sandvold?

2023-12-14 08:22 UTC, stian-sandvold commented
> @Birkbjo interesting! I assume min-max limits are also constrained by the BE's integer validation, but that's just an uneducated guess. Do you know @stian-sandvold?

I don't think we validate those numbers anywhere, but we do store them as ints.

2023-12-14 09:21 UTC, Mohammer5 commented on src/shared/validation/is-integer.js
> +    const exceedsUpperBound = value > 2147483648
Good catch! Unlikely to ever happen in production, but who knows :laughing: I fixed it

2023-12-14 09:21 UTC, Mohammer5 commented on src/shared/validation/is-integer.js
> +    const exceedsLowerBound = value < -2147483648
Ah, also very good catch! I'm using `parseInt` to cast the value as the `integer` validator from our UI library already verifies that it's a valid integer

2023-12-14 09:34 UTC, tomzemp approved these changes
looks good!

2023-12-14 09:42 UTC, Mohammer5 commented
@Birkbjo: confirmed by @stian-sandvold: We can assume that min-max limits also adhere to the integer range restrictions

2023-12-14 09:52 UTC, merged